catalog:
  '@effect/typeclass': ^0.35.14
  '@effect/vitest': 0.24.1
  '@eslint/js': 9.31.0
  '@fast-check/vitest': 0.2.2
  '@tsconfig/node24': 24.0.1
  '@tsconfig/strictest': 2.0.5
  '@types/node': 24.0.15
  '@vitest/coverage-v8': 3.2.4
  dependency-cruiser: 16.10.4
  effect: ^3.16.16
  effect-ts-laws: 1.3.12
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.3
  eslint-plugin-sonarjs: 3.0.4
  eslint-plugin-unicorn: 59.0.1
  eslint: 9.31.0
  fast-check: 4.2.0
  globals: 16.3.0
  jiti: 2.4.2
  prettier: 3.6.2
  ts-graphviz: ^3.0.0
  tsx: 4.20.3
  typedoc: 0.28.7
  typescript-eslint: 8.37.0
  typescript: ~5.8.3
  vitest: 3.2.4

onlyBuiltDependencies:
  - esbuild
