#!/usr/bin/env bash

set -Eeuo pipefail

COLOR="${COLOR:-true}"

. "$(dirname "${0}")/lib/_"

function run() {
  local target svg
  target="${1}" svg="${2}"
  pnpm --silent run "${target}" > doc/examples/tmp.dot
  dot -Tsvg doc/examples/tmp.dot > "doc/examples/${svg}.svg"
  rm doc/examples/tmp.dot
}

run example:class        class
run example:dependencies dependencies
run example:struct       struct
run example:doc-example  doc-example
run example:kitchen-sink kitchen-sink
run example:errors       errors

show_done 'build:examples'

